apiVersion: v1
kind: Service
metadata:
  name: vgdemo-service
  labels:
    app: vgdemo-service
spec:
  selector:
    app: vgdemo-app
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
