apiVersion: v1
kind: Service
metadata:
    name: "vgcluster-43a6"
    labels:
        app: "vgcluster-43a6"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "vgcluster-43a6"