on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    
    - uses: azure/docker-login@v1
      with:
        login-server: vgcontainerdemo.azurecr.io
        username: ${{ secrets.acr_vgcontainerdemo_username }}
        password: ${{ secrets.acr_vgcontainerdemo_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t vgcontainerdemo.azurecr.io/vgcluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push vgcontainerdemo.azurecr.io/vgcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_vgcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep vgclusterae37 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace vgclusterae37`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: vgclusterae37
        container-registry-url: vgcontainerdemo.azurecr.io
        container-registry-username: ${{ secrets.acr_vgcontainerdemo_username }}
        container-registry-password: ${{ secrets.acr_vgcontainerdemo_password }}
        secret-name: vgclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: vgclusterae37
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          vgcontainerdemo.azurecr.io/vgcluster:${{ github.sha }}
        imagepullsecrets: |
          vgclusterdockerauth
